server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: usuarios-service
              uri: ${USUARIOS_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/usuarios/**,/perfiles/**

            - id: entrenamientos-service
              uri: ${ENTRENAMIENTOS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/ejercicios/**,/entrenamientos/**,/entrenamiento-ejercicios/**,/registros/**,/prs/**os/**,/prs/**