spring.application.name=entrenamientos-service
server.port=8082
# Cambiamos el puerto al 8082, no 8081

spring.datasource.url=jdbc:mysql://localhost:3308/entrenamientos_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL base de usuarios-service, la usaremos para las llamadas HTTP entre microservicios
usuarios-service.url=http://localhost:8081